apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka-cluster.yaml
  - kafka-topic.yaml

labels:
  - pairs:
      managed-by: argocd
      component: kafka
    includeSelectors: true
