apiVersion: v1
kind: ConfigMap
metadata:
  name: pega-config
data:
  JDBC_URL: "jdbc:postgresql://postgres-prod:5432/pegadb"
  PEGA_DIAGNOSTIC_USER_ENABLED: "false"
  ENVIRONMENT: "prod"
  CLUSTER_NAME: "eks-prod"
  KAFKA_BOOTSTRAP_SERVERS: "pega-kafka-kafka-bootstrap:9092"
