apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/app
  - ../../base/strimzi
  - ../../base/karpenter

namespace: ops

labels:
  - pairs:
      environment: ops
    includeSelectors: true

patches:
  - path: patches/app-replicas.yaml
  - path: patches/kafka-sizing.yaml
  - path: patches/karpenter-limits.yaml
  - path: patches/ingress-host.yaml
  - path: patches/configmap-env.yaml
