apiVersion: v1
kind: ConfigMap
metadata:
  name: pega-config
data:
  JDBC_URL: "jdbc:postgresql://postgres-trng:5432/pegadb"
  PEGA_DIAGNOSTIC_USER_ENABLED: "true"
  ENVIRONMENT: "trng"
  CLUSTER_NAME: "eks-trng"
  KAFKA_BOOTSTRAP_SERVERS: "pega-kafka-kafka-bootstrap:9092"
