apiVersion: v1
kind: ConfigMap
metadata:
  name: pega-config
data:
  JDBC_URL: "jdbc:postgresql://postgres:5432/pegadb"
  JDBC_CLASS: "org.postgresql.Driver"
  PEGA_DIAGNOSTIC_USER_ENABLED: "true"
  PEGA_APP_CONTEXT_PATH: "prweb"
  CLUSTER_NAME: "default"
  KAFKA_BOOTSTRAP_SERVERS: "pega-kafka-kafka-bootstrap:9092"
