apiVersion: apps/v1
kind: Deployment
metadata:
  name: pega-stream
  labels:
    app: pega-stream
    tier: stream
    app.kubernetes.io/name: pega
    app.kubernetes.io/component: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pega-stream
  template:
    metadata:
      labels:
        app: pega-stream
        tier: stream
        app.kubernetes.io/name: pega
        app.kubernetes.io/component: stream
    spec:
      containers:
        - name: pega-stream
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              name: http
          env:
            - name: NODE_TYPE
              value: "Stream"
            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: pega-config
                  key: JDBC_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: pega-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1g -XX:+UseG1GC"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
