apiVersion: apps/v1
kind: Deployment
metadata:
  name: pega-batch
  labels:
    app: pega-batch
    tier: batch
    app.kubernetes.io/name: pega
    app.kubernetes.io/component: batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pega-batch
  template:
    metadata:
      labels:
        app: pega-batch
        tier: batch
        app.kubernetes.io/name: pega
        app.kubernetes.io/component: batch
    spec:
      containers:
        - name: pega-batch
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              name: http
          env:
            - name: NODE_TYPE
              value: "BackgroundProcessing,Search,Batch"
            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: pega-config
                  key: JDBC_URL
            - name: JAVA_OPTS
              value: "-Xms1g -Xmx2g -XX:+UseG1GC"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
