apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - deployment-batch.yaml
  - deployment-stream.yaml
  - service.yaml
  - configmap-env.yaml
  - configmap-web.yaml
  - configmap-batch.yaml
  - configmap-stream.yaml
  - secret-db.yaml
  - secret-stream.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb-web.yaml
  - pdb-batch.yaml
  - pdb-stream.yaml

labels:
  - pairs:
      managed-by: argocd
      platform: pega
    includeSelectors: true
