apiVersion: v1
kind: Service
metadata:
  name: pega-web
  labels:
    app: pega-web
spec:
  selector:
    app: pega-web
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
