apiVersion: v1
kind: Service
metadata:
  name: pega-web
  labels:
    app: pega-web
spec:
  selector:
    app: pega-web
  ports:
    - port: 80
      targetPort: 80
      name: http
      # Pega production: targetPort 8080
    - port: 443
      targetPort: 443
      name: https
      # Pega production: targetPort 8443
  type: ClusterIP
