apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nodepool.yaml
  - ec2nodeclass.yaml

labels:
  - pairs:
      managed-by: argocd
      component: karpenter
    includeSelectors: true
