apiVersion: v1
kind: ConfigMap
metadata:
  name: pega-env-config
data:
  DB_TYPE: "postgresql"
  JDBC_URL: "jdbc:postgresql://postgres-ops:5432/pegadb"
  RULES_SCHEMA: "rules"
  DATA_SCHEMA: "data"
  PEGA_DIAGNOSTIC_USER_ENABLED: "true"
  ENVIRONMENT: "ops"
  CLUSTER_NAME: "eks-ops"
  STREAM_BOOTSTRAP_SERVERS: "pega-kafka-kafka-bootstrap:9092"
