apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pega-web
spec:
  rules:
    - host: pega-ops.local
      http:
        paths:
          - path: /prweb
            pathType: Prefix
            backend:
              service:
                name: pega-web
                port:
                  number: 80
